In [1]:
import numpy as np
import pandas as pd

In [ ]:
# {Climate, Sightseeing, Environment}

In [2]:
# Number of options
n = 3
# Creating default matrix of ones
A = np.ones([n,n])
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
# Running a for loop to take input from user and populate the upper triangular elements
for i in range(0,n):
    for j in range(0,n):
         if i<j:
             aij = input('How important is option{} over option{} ?: '.format(i,j))
             A[i,j] = float(aij) #Upper triangular elements
             A[j,i] = 1/float(aij) #Lower triangular elements

In [4]:
e = np.linalg.eig(A)[1][:,0]
p = e/e.sum()

In [ ]:
def pairwise_matrix(n):
A = np.ones([n,n])
    for i in range(0,n):
        for j in range(0,n):
            if i<j:
                aij = input('How important is option{} over option{} ?: '.format(i,j))
                A[i,j] = float(aij)
                A[j,i] = 1/float(aij)
#Computing the priority vector 
    eig_val = np.linalg.eig(A)[0].max()
    eig_vec = np.linalg.eig(A)[1][:,0]
    p = eig_vec/eig_vec.sum()
    return p, eig_val

In [ ]:
['A', 'C', 'A', 'A', 'C', 'D', 'B', 'C', 'E', 'D']
[8, 6, 1, 1, 4, 6, 1, 2, 9, 7]

In [179]:
kriteria_inputs = ['Price', 'RAM', 'HDD', 'Weight']
pref_kriteria_inputs = ['Price', 'Price', 'Price', 'HDD', 'RAM', 'HDD']
valpref_kriteria_inputs = [5, 4, 7, 2, 3, 3]

start_index = 0
amount_kriteria = 4
tot = int((amount_kriteria*(amount_kriteria+1))/2)
pref_krit_split = []
valpref_krit_split = []

for i in range(amount_kriteria-1, 0, -1):
    sublist1 = pref_kriteria_inputs[start_index:start_index + i]
    sublist2 = valpref_kriteria_inputs[start_index:start_index + i]
    pref_krit_split.append(sublist1)
    valpref_krit_split.append(sublist2)
    start_index += i

print(pref_krit_split)
print(valpref_krit_split)

[['Price', 'Price', 'Price'], ['HDD', 'RAM'], ['HDD']]
[[5, 4, 7], [2, 3], [3]]


In [183]:
kriteria_inputs[0]

'Price'

In [181]:
matrix = np.zeros((amount_kriteria, amount_kriteria))
np.fill_diagonal(matrix, 1)
for row in range(len(matrix)-1):
    check_count = 0
    check_len = len(pref_krit_split[row])

    for ele in range(row+1, len(matrix)):
        if pref_krit_split[row][check_count] == kriteria_inputs[row]:
            print('DEF')
            matrix[row][ele] = valpref_krit_split[row][check_count]
        else:
            print('FLIP')
            matrix[ele][row] = valpref_krit_split[row][check_count]
        check_count += 1
        if check_count == check_len: break

FLIP
FLIP
FLIP
FLIP
FLIP
FLIP


In [177]:
matrix

array([[1., 0., 0., 0.],
       [5., 1., 0., 0.],
       [4., 2., 1., 0.],
       [7., 3., 3., 1.]])

In [178]:
for row in range(len(matrix)):
    for ele in range(len(matrix)):
        if matrix[row][ele] == 0:
            matrix[row][ele] = 1/matrix[ele][row]

In [169]:
matrix

array([[1.        , 5.        , 4.        , 7.        ],
       [0.2       , 1.        , 0.5       , 3.        ],
       [0.25      , 2.        , 1.        , 3.        ],
       [0.14285714, 0.33333333, 0.33333333, 1.        ]])

In [170]:
transposed_matrix = matrix.copy()
transposed_matrix = transposed_matrix.transpose()
for row in range(len(transposed_matrix)):
    row_sum = sum(transposed_matrix[row])
    for ele in range(len(transposed_matrix)):
        transposed_matrix[row][ele] = round(transposed_matrix[row][ele] / row_sum, 2)
transposed_matrix

array([[0.63, 0.13, 0.16, 0.09],
       [0.6 , 0.12, 0.24, 0.04],
       [0.69, 0.09, 0.17, 0.06],
       [0.5 , 0.21, 0.21, 0.07]])

In [171]:
norm_matrix = transposed_matrix.copy().transpose()
norm_matrix

array([[0.63, 0.6 , 0.69, 0.5 ],
       [0.13, 0.12, 0.09, 0.21],
       [0.16, 0.24, 0.17, 0.21],
       [0.09, 0.04, 0.06, 0.07]])

In [172]:
criteria_weight = [round(sum(row)/len(row), 2) for row in norm_matrix]
criteria_weight

[0.6, 0.14, 0.2, 0.06]

In [145]:
rand_idx_dict ={3: 0.58,
                4: 0.9,
                5: 1.12,
                6: 1.24,
                7: 1.32,
                8: 1.41,
                9: 1.45,
                10: 1.49,
                11: 1.51,
                12: 1.48,
                13: 1.56,
                14: 1.57,
                15: 1.58}

In [173]:
matrix_x = np.dot(matrix, np.array(criteria_weight).transpose())
lambda_max = sum([matrix_x[i]/criteria_weight[i] for i in range(len(criteria_weight))])/len(criteria_weight)
cons_idx = (lambda_max-amount_kriteria)/(amount_kriteria)
rand_idx = rand_idx_dict.get(amount_kriteria)
cons_ratio = cons_idx/rand_idx
cons_ratio

0.029486331569664858

In [174]:
criteria_weight

[0.6, 0.14, 0.2, 0.06]

In [152]:
np.argsort(criteria_weight)

array([2, 3, 4, 0, 1], dtype=int64)

In [164]:
import matplotlib.pyplot as plt

In [163]:
sort_krit_weight = np.array(criteria_weight)[np.argsort(criteria_weight)].tolist()
sort_krit_inputs = np.array(kriteria_inputs)[np.argsort(criteria_weight)].tolist()
plt.hist()

NameError: name 'hist' is not defined

In [105]:
tes_m = [[1,0.5,3],[2,1,4],[0.333,0.25,1]]
tes_m = np.array(tes_m)
np.dot(tes_m, np.array([0.32,0.56,0.12]).transpose())

array([0.96   , 1.68   , 0.36656])

In [17]:
def fill_upper_triangle(matrix, values):
    if len(values) != len(matrix) - 1:
        raise ValueError("Number of values should be one less than the size of the matrix diagonal.")

    n = len(matrix)
    for i in range(n):
        for j in range(i+1, n):
            matrix[i][j] = values[j-1]

# Example usage:
matrix = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
]

values = [1, 2]
fill_upper_triangle(matrix, values)

# Print the filled matrix
for row in matrix:
    print(row)

[0, 1, 2]
[0, 0, 2]
[0, 0, 0]


In [ ]:
for i in range()